MAP_AREAS = (
    ('ranaka', 'ranaka'),
    ('digawana', 'digawana'),
    ('molapowabojang', 'molapowabojang'),
    ('otse', 'otse')
    ('letlhakeng', 'letlhakeng'),
    ('lentsweletau', 'lentsweletau')
    ('bokaa', 'bokaa'),
    ('oodi', 'oodi')
    ('mmathethe', 'mmathethe'),
    ('mmankgodi', 'mmankgodi')
    ('sefophe', 'sefophe'),
    ('lerala', 'lerala')
    ('ramokgonami', 'ramokgonami'),
    ('maunatlala', 'maunatlala')
    ('mmadinare', 'mmadinare'),
    ('shoshosng', 'shoshosng')
    ('metsimotlhabe', 'metsimotlhabe'),
    ('tati_siding', 'tati_siding')
    ('sebina', 'sebina'),
    ('nkange', 'nkange')
    ('mmandunyane', 'mmandunyane'),
    ('mathangwane', 'mathangwane')
    ('rakops', 'rakops'),
    ('gweta', 'gweta')
    ('shakawe', 'shakawe'),
    ('gumare', 'gumare')
    ('tsetsebjwe', 'tsetsebjwe'),
    ('sefhare', 'sefhare')
    ('nata', 'nata'),
    ('masunga', 'masunga')
)
